version: 2

models:
  - name: kpi_job_offers_by_type_with_salary
    description: KPI showing job offers by type with salary details.

  - name: kpi_job_postings_by_experience
    description: KPI showing job postings by experience.

  - name: kpi_job_role_distribution_by_gender
    description: KPI on job roles offered based on gender.

  - name: kpi_job_vacancy_trends
    description: Trends over time for job vacancies.

  - name: kpi_location_opportunities
    description: KPI showing opportunities by location.

  - name: kpi_urgent_openings
    description: Jobseeker view of urgent jobs.
